name: Add dev stack
on:
  schedule:
    - cron:  '20 20 * * *'
  push:
    branches: 
      - master

jobs:
  add-dev-stack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: vithano/add-dev-stack@master
      with:
        DEV_STACK: '### Dev stack'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: '/README.md'
        COMMIT_MESSAGE: 'docs(README): update dev stack'
        TYPES_TO_SHOW: 'Package manager,Monorepo manager,Frontend,Frontend css,Server-Client communication,Backend,ORM,Testing,Testing components,Component library,Test mocks,Lint'
