name: Add dev stack
on:
  push:
    branches: 
      - dev

jobs:
  add-dev-stack:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: vithano/add-dev-stack@dev
      with:
        REPO_NAME: 'vithano/add-dev-stack'
        DEV_STACK: '### Dev stack'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '100'
        FONT_SIZE: '14'
        PATH: 'dev:/README.md'
        COMMIT_MESSAGE: 'docs(README): update dev stack'
        AVATAR_SHAPE: 'round'
        PACKAGES_TO_SHOW: 'all'
